#!/usr/bin/env python3
"""
compare_iv.py — Statistical Comparison of MOSFET IV Curves
===========================================================
Compares a REFERENCE dataset (B2902B format) against a MEASURED dataset
(ESP32 firmware CSV format), computing per-curve statistical metrics per VDS.

Metrics per curve (per VDS value):
  • RMSE    — Root Mean Square Error
  • R²      — Coefficient of Determination
  • χ²      — Reduced Chi-Squared (consistency with measurement noise)
  • Var     — Residual Variance
  • σ       — Residual Standard Deviation

Usage:
  python compare_iv.py <reference.csv> <measured.csv> [--output out.pdf] [--log] [--no-show]

Example:
  python compare_iv.py "IVG-Triodo - 1 BS170 - 1.csv" "triodoBS170_noOversampling.csv"
"""

import argparse
import sys
import os
import warnings
import numpy as np
import pandas as pd

# Force a non-interactive backend when there is no display available
import matplotlib
if not os.environ.get("DISPLAY") and not os.environ.get("WAYLAND_DISPLAY"):
    matplotlib.use("Agg")

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
from matplotlib.ticker import LogLocator, LogFormatter
from scipy.interpolate import interp1d

# ─── Constants ───────────────────────────────────────────────────────────────

VDS_TOL        = 0.015        # Tolerance for matching VDS values between datasets (V)
EPS            = 1e-15        # Guard against division by zero in chi-squared
CURRENT_UNIT   = "A"          # Current unit label
VDS_ROUND      = 3            # Decimal places for VDS comparison

# Colour palette
COLOR_REF  = "#2196F3"        # Blue  → reference
COLOR_MEAS = "#F44336"        # Red   → measured

# ─── Data Parsers ─────────────────────────────────────────────────────────────

def parse_b2902b(path: str) -> pd.DataFrame:
    """
    Read a CSV file in the proprietary B2902B (Keysight) format.
    Locates DataName and DataValue rows and extracts Vg (VGS), Vd (VDS), Id (IDS).

    Returns a DataFrame with columns: vgs [V], vds [V], ids [A]
    """
    header = None
    rows = []

    with open(path, encoding="utf-8-sig", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n\r")
            if line.startswith("DataName"):
                parts = [x.strip() for x in line.split(",")]
                header = parts[1:]          # remove 'DataName' tag
            elif line.startswith("DataValue"):
                if header is None:
                    continue
                parts = [x.strip() for x in line.split(",")]
                values = parts[1:]
                d = dict(zip(header, values))
                try:
                    rows.append({
                        "vgs": float(d["Vg"]),
                        "vds": float(d["Vd"]),
                        "ids": float(d["Id"]),
                    })
                except (KeyError, ValueError):
                    continue

    if not rows:
        raise ValueError(f"No DataValue entries found in: {path}")

    df = pd.DataFrame(rows)
    print(f"[B2902B] Loaded: {len(df)} points | "
          f"VDS: {sorted(df['vds'].round(VDS_ROUND).unique())} V")
    return df


def parse_esp32_csv(path: str) -> pd.DataFrame:
    """
    Read a CSV file generated by the ESP32 firmware.
    Skips comment lines (#) and treats the first non-comment line as the header.
    Expected columns: timestamp, vds, vgs, vsh, ids (or any subset containing vds, vgs, ids).

    Returns a DataFrame with columns: vgs [V], vds [V], ids [A]
    """
    rows = []
    header = None

    with open(path, encoding="utf-8-sig", errors="replace") as f:
        for line in f:
            line = line.rstrip("\n\r")
            if not line or line.startswith("#"):
                continue
            parts = [x.strip() for x in line.split(",")]
            if header is None:
                header = [h.lower() for h in parts]
                continue
            if len(parts) < len(header):
                continue
            d = dict(zip(header, parts))
            try:
                rows.append({
                    "vgs": float(d["vgs"]),
                    "vds": float(d["vds"]),
                    "ids": float(d["ids"]),
                })
            except (KeyError, ValueError):
                continue

    if not rows:
        raise ValueError(f"No data found in: {path}")

    df = pd.DataFrame(rows)
    print(f"[ESP32 ] Loaded: {len(df)} points | "
          f"VDS: {sorted(df['vds'].round(VDS_ROUND).unique())} V")
    return df


def auto_detect_format(path: str) -> pd.DataFrame:
    """Detect the file format automatically and call the appropriate parser."""
    with open(path, encoding="utf-8-sig", errors="replace") as f:
        first_lines = [f.readline() for _ in range(5)]

    content = "".join(first_lines)
    if "DataName" in content or "DataValue" in content or "SetupTitle" in content:
        return parse_b2902b(path)
    elif "MOSFET Characterization" in content or "vds" in content.lower():
        return parse_esp32_csv(path)
    else:
        # Try B2902B first, then fall back to ESP32 format
        try:
            return parse_b2902b(path)
        except ValueError:
            return parse_esp32_csv(path)


# ─── Statistical Metrics ─────────────────────────────────────────────────────

def compute_statistics(ref_ids: np.ndarray, meas_ids: np.ndarray) -> dict:
    """
    Calcula métricas estatísticas entre correntes de referência e medida.

    Parâmetros
    ----------
    ref_ids  : array de correntes da referência (valores "verdadeiros")
    meas_ids : array de correntes da medida (valores interpolados nos pontos da ref)

    Retorna dicionário com:
        rmse  — Root Mean Square Error [A]
        r2    — Coeficiente de determinação [adimensional]
        chi2  — Qui-quadrado reduzido [adimensional]
        var   — Variância dos resíduos [A²]
        std   — Desvio padrão dos resíduos [A]
        n     — Número de pontos usados
        mean_residual — Média dos resíduos [A]
    """
    n = len(ref_ids)
    if n < 2:
        return dict(rmse=np.nan, r2=np.nan, chi2=np.nan, var=np.nan, std=np.nan,
                    n=n, mean_residual=np.nan)

    residuals = ref_ids - meas_ids
    mean_ref  = np.mean(ref_ids)

    # RMSE
    rmse = np.sqrt(np.mean(residuals**2))

    # R²
    ss_res = np.sum(residuals**2)
    ss_tot = np.sum((ref_ids - mean_ref)**2)
    r2 = 1.0 - (ss_res / ss_tot) if ss_tot > EPS else np.nan

    # Reduced chi-squared (normalised by |meas|² to be scale-independent)
    denominator = np.maximum(np.abs(meas_ids)**2, EPS)
    chi2 = np.mean(residuals**2 / denominator)

    # Residual variance and standard deviation
    var = np.var(residuals, ddof=1)
    std = np.std(residuals, ddof=1)

    # Mean residual (systematic bias)
    mean_residual = np.mean(residuals)

    return dict(rmse=rmse, r2=r2, chi2=chi2, var=var, std=std,
                n=n, mean_residual=mean_residual)


# ─── Unit Formatting ─────────────────────────────────────────────────────────

def fmt_current(val: float, decimals: int = 3) -> str:
    """Format a current value with an appropriate SI prefix."""
    if np.isnan(val):
        return "N/A"
    abs_val = abs(val)
    if abs_val == 0:
        return "0 A"
    elif abs_val >= 1e-3:
        return f"{val*1e3:.{decimals}f} mA"
    elif abs_val >= 1e-6:
        return f"{val*1e6:.{decimals}f} µA"
    elif abs_val >= 1e-9:
        return f"{val*1e9:.{decimals}f} nA"
    elif abs_val >= 1e-12:
        return f"{val*1e12:.{decimals}f} pA"
    else:
        return f"{val:.2e} A"


def fmt_current_sq(val: float) -> str:
    """Format an A² value (residual variance)."""
    if np.isnan(val):
        return "N/A"
    abs_val = abs(val)
    if abs_val >= 1e-6:
        return f"{val*1e6:.3e} µA²"
    elif abs_val >= 1e-12:
        return f"{val*1e12:.3e} pA²"
    else:
        return f"{val:.2e} A²"


# ─── Plotting ─────────────────────────────────────────────────────────────────

def plot_vds_panel(ax: plt.Axes,
                   vds_val: float,
                   ref_sub: pd.DataFrame,
                   meas_sub: pd.DataFrame,
                   meas_interp: np.ndarray,
                   stats: dict,
                   use_log: bool,
                   ref_label: str,
                   meas_label: str) -> None:
    """
    Plot a single panel for one VDS value:
      - Overlaid IDS × VGS curves (log or linear scale)
      - Annotated metrics table inside the axes
    """
    # ── Curves ──
    ax.plot(ref_sub["vgs"].values,
            np.abs(ref_sub["ids"].values),
            color=COLOR_REF,
            linewidth=1.8,
            label=ref_label,
            zorder=3)

    ax.plot(meas_sub["vgs"].values,
            np.abs(meas_sub["ids"].values),
            color=COLOR_MEAS,
            linewidth=1.5,
            linestyle="--",
            alpha=0.9,
            label=meas_label,
            zorder=3)

    # Eixos
    vgs_min  = min(ref_sub["vgs"].min(), meas_sub["vgs"].min())
    vgs_max  = max(ref_sub["vgs"].max(), meas_sub["vgs"].max())

    ax.set_xlim(vgs_min, vgs_max)
    ax.set_xlabel("V$_{GS}$ (V)", fontsize=8)
    ax.set_ylabel("|I$_{DS}$| (A)", fontsize=8)
    ax.set_title(f"V$_{{DS}}$ = {vds_val:.3f} V", fontsize=9, fontweight="bold", pad=4)
    ax.tick_params(labelsize=7)
    ax.grid(True, which="both", linestyle="--", linewidth=0.4, alpha=0.5)
    ax.legend(fontsize=6, loc="upper left", framealpha=0.7)

    if use_log:
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            ax.set_yscale("log")

    # ── Metrics box ──
    r2_str   = f"{stats['r2']:.5f}"   if not np.isnan(stats['r2'])   else "N/A"
    chi2_str = f"{stats['chi2']:.4e}" if not np.isnan(stats['chi2']) else "N/A"

    metrics_text = (
        f"N = {stats['n']}\n"
        f"RMSE = {fmt_current(stats['rmse'])}\n"
        f"R²   = {r2_str}\n"
        f"χ²   = {chi2_str}\n"
        f"Var  = {fmt_current_sq(stats['var'])}\n"
        f"σ    = {fmt_current(stats['std'])}\n"
        f"Bias = {fmt_current(stats['mean_residual'])}"
    )

    ax.text(0.98, 0.02, metrics_text,
            transform=ax.transAxes,
            fontsize=6.5,
            verticalalignment="bottom",
            horizontalalignment="right",
            fontfamily="monospace",
            bbox=dict(boxstyle="round,pad=0.4", facecolor="#F5F5F5",
                      edgecolor="#BDBDBD", alpha=0.92))


# ─── Main ─────────────────────────────────────────────────────────────────────

def find_common_vds(ref_df: pd.DataFrame,
                    meas_df: pd.DataFrame,
                    tol: float = VDS_TOL) -> list[float]:
    """
    Encontra valores de VDS presentes em ambos os datasets (com tolerância).
    Retorna lista de VDS da referência que têm correspondência na medida.
    """
    ref_vds  = sorted(ref_df["vds"].unique())
    meas_vds = sorted(meas_df["vds"].unique())

    common = []
    for rv in ref_vds:
        for mv in meas_vds:
            if abs(rv - mv) <= tol:
                common.append(rv)
                break

    return common


def get_meas_subset_for_vds(meas_df: pd.DataFrame,
                              ref_vds: float,
                              tol: float = VDS_TOL) -> pd.DataFrame:
    """Return the measured subset matching a reference VDS (within tolerance)."""
    mask = np.abs(meas_df["vds"] - ref_vds) <= tol
    return meas_df[mask].copy().sort_values("vgs").reset_index(drop=True)


def main():
    parser = argparse.ArgumentParser(
        description="Statistical comparison of MOSFET IV curves"
    )
    parser.add_argument("referencia",  help="Reference CSV file (B2902B or ESP32 format)")
    parser.add_argument("medida",      help="Measured CSV file (B2902B or ESP32 format)")
    parser.add_argument("--output",    default=None,
                        help="Output file (PDF/PNG), e.g.: result.pdf")
    parser.add_argument("--no-show",   action="store_true",
                        help="Skip the interactive plot window")
    parser.add_argument("--log",       action="store_true",
                        help="Use logarithmic scale on the current axis")
    parser.add_argument("--no-log",    action="store_true",
                        help="Force linear scale (overrides --log)")
    args = parser.parse_args()

    use_log = args.log and not args.no_log

    print("\n" + "═"*60)
    print(" IV CURVE STATISTICAL COMPARISON — MOSFET")
    print("═"*60)
    print(f" Reference : {args.referencia}")
    print(f" Measured  : {args.medida}")
    print(f" Y scale   : {'logarithmic' if use_log else 'linear'}")
    print("─"*60 + "\n")

    # ── Load datasets ──
    ref_df  = auto_detect_format(args.referencia)
    meas_df = auto_detect_format(args.medida)

    # ── Find common VDS values ──
    common_vds = find_common_vds(ref_df, meas_df)
    if not common_vds:
        print("[ERROR] No VDS values in common between files (tolerance ±"
              f"{VDS_TOL} V).")
        print(f"  Reference : {sorted(ref_df['vds'].round(3).unique())}")
        print(f"  Measured  : {sorted(meas_df['vds'].round(3).unique())}")
        sys.exit(1)

    print(f"\n✔ Common VDS values found: {[round(v,3) for v in common_vds]}\n")

    # ── Figure layout ──
    ncols = 3
    nrows = int(np.ceil(len(common_vds) / ncols))
    fig_w = ncols * 5.0
    fig_h = nrows * 4.2

    fig = plt.figure(figsize=(fig_w, fig_h), facecolor="#FAFAFA")
    fig.suptitle(
        "Statistical Comparison: I$_{DS}$ \u00d7 V$_{GS}$ Curves by V$_{DS}$\n"
        f"Reference: {args.referencia.split('/')[-1]}   \u2022   "
        f"Measured: {args.medida.split('/')[-1]}",
        fontsize=11, fontweight="bold", y=0.995
    )

    gs = gridspec.GridSpec(nrows, ncols, figure=fig,
                           hspace=0.55, wspace=0.38,
                           left=0.06, right=0.98,
                           top=0.94, bottom=0.05)

    # Short labels for the legend
    ref_label  = "Ref. B2902B"
    meas_label = "ESP32"

    # ── Tabela de resumo no terminal ──
    print(f"{'VDS (V)':>8} | {'N':>5} | {'RMSE':>12} | {'R²':>8} | "
          f"{'χ²':>10} | {'Var':>12} | {'σ':>12}")
    print("─"*85)

    all_stats = []

    for idx, vds_val in enumerate(common_vds):
        row = idx // ncols
        col = idx % ncols
        ax  = fig.add_subplot(gs[row, col])

        ref_sub  = ref_df[np.abs(ref_df["vds"] - vds_val) <= VDS_TOL].copy()
        ref_sub  = ref_sub.sort_values("vgs").reset_index(drop=True)

        meas_sub = get_meas_subset_for_vds(meas_df, vds_val)

        # Interpolação da medida nos pontos VGS da referência
        vgs_ref   = ref_sub["vgs"].values
        vgs_meas  = meas_sub["vgs"].values
        ids_meas  = meas_sub["ids"].values

        vgs_min_common = max(vgs_ref.min(), vgs_meas.min())
        vgs_max_common = min(vgs_ref.max(), vgs_meas.max())

        mask_ref = (vgs_ref >= vgs_min_common) & (vgs_ref <= vgs_max_common)

        if mask_ref.sum() < 2 or len(vgs_meas) < 2:
            print(f"{vds_val:>8.3f} |     — | [insufficient data for interpolation]")
            ax.set_title(f"V$_{{DS}}$ = {vds_val:.3f} V — no data", fontsize=9)
            ax.axis("off")
            continue

        try:
            interp_fn   = interp1d(vgs_meas, ids_meas,
                                   kind="linear",
                                   bounds_error=False,
                                   fill_value="extrapolate")
            meas_interp = interp_fn(vgs_ref[mask_ref])
        except Exception as e:
            print(f"[WARNING] Interpolation failed for VDS={vds_val:.3f}: {e}")
            meas_interp = np.interp(vgs_ref[mask_ref], vgs_meas, ids_meas)

        stats = compute_statistics(ref_sub["ids"].values[mask_ref], meas_interp)
        all_stats.append({"vds": vds_val, **stats})

        plot_vds_panel(ax, vds_val,
                       ref_sub, meas_sub,
                       meas_interp, stats,
                       use_log,
                       ref_label, meas_label)

        # Linha do terminal — extrair strings antes do print p/ evitar f-string aninhada
        r2_str_t   = f"{stats['r2']:.5f}"   if not np.isnan(stats['r2'])   else "N/A"
        chi2_str_t = f"{stats['chi2']:.3e}" if not np.isnan(stats['chi2']) else "N/A"
        print(f"{vds_val:>8.3f} | {stats['n']:>5d} | "
              f"{fmt_current(stats['rmse']):>12} | "
              f"{r2_str_t:>8} | "
              f"{chi2_str_t:>10} | "
              f"{fmt_current(stats['var']):>12} | "
              f"{fmt_current(stats['std']):>12}")

    print("─"*85 + "\n")

    # ── Hide extra panel slots ──
    total_panels = nrows * ncols
    for extra_idx in range(len(common_vds), total_panels):
        row_e = extra_idx // ncols
        col_e = extra_idx % ncols
        ax_e  = fig.add_subplot(gs[row_e, col_e])
        ax_e.axis("off")

    # ── Save / Show ──
    if args.output:
        fig.savefig(args.output, dpi=200, bbox_inches="tight")
        print(f"✔ Figure saved to: {args.output}\n")

    if not args.no_show:
        plt.show()
    else:
        plt.close(fig)


if __name__ == "__main__":
    main()
